feat: vite
Qbox-project/npwd_qbx_garages pull request #3
Opened 2024-01-12 00:26 UTC by BerkieBb

## Description

Fixes the app

WIP as a fatal error is now on the screen when you open the app but at least it loads now.

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-01-20 00:34 UTC, itschip requested changes

2024-01-20 00:34 UTC, itschip commented on src/App.tsx
> +import { NuiProvider } from 'fivem-nui-react-lib';
You don't actually need this. Just use the `useNuiHook` from npwd (copy-paste) into the codebase. No need for the lib here.

2024-01-20 00:34 UTC, itschip commented on src/App.tsx
>  import styled from 'styled-components';
Replace styled-components with `@emotion/styled`

2024-01-20 00:34 UTC, itschip commented on src/App.tsx
> +    <NuiProvider resource="npwd_qbx_garages">
As ur removing the nui lib, remove `NuiProvider`

2024-01-20 00:34 UTC, itschip commented on vite.config.ts
> +        "fivem-nui-react-lib",
Remove `fivem-nui-react-lib`

2024-01-21 02:54 UTC, itschip reviewed
LTGM

2024-01-21 02:54 UTC, itschip commented on src/App.tsx
> +    }, {});
You can just do this directly in the fetchNui promise chain :)

2024-01-21 17:00 UTC, MafewTM approved these changes

2024-02-11 18:22 UTC, merged